## Container based media tools configuration
##
## Configuration items for this file are taken from the .env file
##
## Have docker-compose.yml and .env in the same directory to launch the stack

version: "3.3"

######################
# SERVICES TO LAUNCH #
######################

services:
  # ----------------------------------------
  # TRAEFIK
  # Reverse Proxy + SSL Support
  # ----------------------------------------
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "providers.docker.network=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  # ----------------------------------------
  # WHOAMI
  # Simple Service for Testing
  # ----------------------------------------
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "providers.docker.network=web"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  # ----------------------------------------
  # PORTAINER
  # Docker Container Management
  # ----------------------------------------
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - web
    ports:
      - 9000:9000
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "./portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "providers.docker.network=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"

#   # ----------------------------------------
#   # PLEX
#   # Robust Media Server
#   # ----------------------------------------
#   plex:
#     container_name: plex
#     image: plexinc/pms-docker:${PMSTAG}
#     restart: unless-stopped
#     networks:
#       - web
#     ports:
#       - "32400:32400/tcp"
#       - "8324:8324/tcp"
#       - "32469:32469/tcp"
#       - "1900:1900/udp"
#       - "32410:32410/udp"
#       - "32412:32412/udp"
#       - "32413:32413/udp"
#       - "32414:32414/udp"
#     environment:
#       - TZ=${TZ}
#       - PLEX_CLAIM=${PMSTOKEN}
#       - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
#     hostname: ${HOSTNAME}
#     volumes:
#       - "./plex:/config"
#       - "./plex/transcode:/transcode"
#       - "${ROOT_DIR}/media/Movies:/data/movies"
#       - "${ROOT_DIR}/media/TVShows:/data/tvshows"
#       - "/etc/localtime:/etc/localtime:ro"
#     labels:
#       - "traefik.enable=true"
#       - "providers.docker.network=web"
#       - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
#       - "traefik.http.services.plex.loadbalancer.server.port=32400"
#       - "traefik.http.routers.plex.entrypoints=websecure"
#       - "traefik.http.routers.plex.tls=true"
#       - "traefik.http.routers.plex.tls.certresolver=myresolver"

  # ----------------------------------------
  # General Purpose Container
  # ----------------------------------------
  networks:
    web:
      external: true
